### ISSUE TITLE
error in multiprocessing when using current NumPy version

### ISSUE THREAD

**Issue by thaynecurrie** [t-brandt/orvara#64]
Following some of the recent Issues (#60, #62), I edited the orvara source code to remove instances of np.float and np.int and modify .join on the pyplot shareaxis calls. 

 [I also got Taichi Uyama's error of a mismatch of on the PA and rel-separation output plots between the top and bottom panels but fixed it with a hardcoded sharex command as here: https://stackoverflow.com/questions/77418896/attributeerror-grouperview-object-has-no-attribute-join.]

 This gets orvara to run with the current version of NumPy (1.26.4) using one thread.

However, when I attempt to use multiple threads for parallelization, I get a 
"AttributeError: 'NoneType' object has no attribute 'nInst'"
 on line 206 of main.py  .

Is there a quick workaround to this?   I am running with Python 3.12 on an Macbook M3 Max and NumPy 1.26.4.  On my older laptop running Numpy 1.22.6 and orvara 1.1.2 I get no errors.

---
Running MCMC ... 
[                              ]  0%multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/thaynecurrie/anaconda3/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/thaynecurrie/anaconda3/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/Users/thaynecurrie/anaconda3/lib/python3.12/site-packages/ptemcee/sampler.py", line 137, in __call__
    ll = self.logl(x, *self.loglargs, **self.loglkwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thaynecurrie/Research/Github/repositories/orvara_py311/orvara/orvara/main.py", line 253, in avoid_pickle_lnprob
    return lnprob(theta, **_loglkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thaynecurrie/Research/Github/repositories/orvara_py311/orvara/orvara/main.py", line 206, in lnprob
    params = orbit.Params(theta, i, nplanets, data.nInst, njitters)
                                              ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'nInst'
"""

**Comment by frica2025** [comment]
I am installing ORVARA in a Windows PC, and I have several problems:

* dependences with pytest for example
* codes of characters in Windows
* problems with emcee : emcee.PTSampler is obsolete
* problemas with numpy: np.float is obsolete

I think that I have just solved the problems (I am runnung ORVARa and MCMC is still working).

**I have modified MAIN.PY of ORVARA** 

search the line 340. Replace the block:

try:
    sample0 = emcee.PTSampler(...)
except:
    sample0 = PTSampler(...)

by:

#from ptemcee import Sampler as PTSampler #comment this line
import ptemcee #add this line


sample0 = ptemcee.Sampler(
    ntemps=ntemps,
    nwalkers=nwalkers,
    dim=ndim,
    logl=avoid_pickle_lnprob,
    logp=return_one,
    threads=nthreads
)

**then modify sampler.py** in

 C:\Users\<user>\AppData\Local\Programs\Python\Python312\Lib\site-packages\ptemcee\sampler.py

replaceing np.float for np.float64

there are about 6 lineas of codes to replace
